site_offre_emploi/urls.py
from django.contrib import admin
from django.urls import path
from my_app.views import *
from django.contrib.auth.views import *
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('connexion_admin/', connexion_admin, name='connexion_admin'),
    path('deconnexion/', deconnexion, name='deconnexion'),
    path('dashboard/', dashboard, name='dashboard'),
    path('supprimer_user/<int:user_id>/', supprimer_user, name='supprimer_user'),
    path('ajouter_user/', ajouter_user, name='ajouter_user'),
    path('modifier_user/<int:user_id>/', modifier_user, name='modifier_user'),
    path('ajouter_candidat/', ajouter_candidat, name='ajouter_candidat'),
    path('modifier_candidat/<int:candidat_id>/', modifier_candidat, name='modifier_candidat'),
    path('supprimer_candidat/<int:candidat_id>/', supprimer_candidat, name='supprimer_candidat'),
    path('ajouter_entreprise/', ajouter_entreprise, name='ajouter_entreprise'),
    path('modifier_entreprise/<int:entreprise_id>/', modifier_entreprise, name='modifier_entreprise'),
    path('supprimer_entreprise/<int:entreprise_id>/', supprimer_entreprise, name='supprimer_entreprise'),
    path('ajouter_emploi/', ajouter_emploi, name='ajouter_emploi'),
    path('modifier_emploi/<int:emploi_id>/', modifier_emploi, name='modifier_emploi'),
    path('supprimer_emploi/<int:emploi_id>/', supprimer_emploi, name='supprimer_emploi'),
    path('ajouter_postulation/', ajouter_postulation, name='ajouter_postulation'),
    path('modifier_postulation/<int:postulation_id>/', modifier_postulation, name='modifier_postulation'),
    path('supprimer_postulation/<int:postulation_id>/', supprimer_postulation, name='supprimer_postulation'),
    path('rechercher_emplois/', rechercher_emplois, name='rechercher_emplois'),
    path('ajouter_experience/', ajouter_experience, name='ajouter_experience'),
    path('modifier_experience/<int:experience_id>/', modifier_experience, name='modifier_experience'),
    path('supprimer_experience/<int:experience_id>/', supprimer_experience, name='supprimer_experience'),
    path('ajouter_competence/', ajouter_competence, name='ajouter_competence'),
    path('modifier_competence/<int:competence_id>/', modifier_competence, name='modifier_competence'),
    path('supprimer_competence/<int:competence_id>/', supprimer_competence, name='supprimer_competence'),
    path('ajouter_formation/', ajouter_formation, name='ajouter_formation'),
    path('modifier_formation/<int:formation_id>/', modifier_formation, name='modifier_formation'),
    path('supprimer_formation/<int:formation_id>/', supprimer_formation, name='supprimer_formation'),
    path('offre_emploi_detail/<int:emploi_id>/', offre_emploi_detail, name='offre_emploi_detail'),
    path('postuler_emploi/<int:emploi_id>/', postuler_emploi, name='postuler_emploi'),
    path('mes_candidatures/<int:candidat_id>/', mes_candidatures, name='mes_candidatures'),
    path('inscription_candidat/', inscription_candidat, name='inscription_candidat'),
    path('connexion_candidat/', connexion_candidat, name='connexion_candidat'),
    path('profil_candidat/', profil_candidat, name='profil_candidat'),
    path('modifier_profile_candidat/<int:candidat_id>', modifier_profile_candidat, name='modifier_profile_candidat'),
    path('ajouterCompetence/', ajouterCompetence, name='ajouterCompetence'),
    path('modifierCompetence/<int:competence_id>/', modifierCompetence, name='modifierCompetence'),
    path('supprimerCompetence/<int:competence_id>/', supprimerCompetence, name='supprimerCompetence'),
    path('ajouterExperience/', ajouterExperience, name='ajouterExperience'),
    path('modifierExperience/<int:experience_id>/', modifierExperience, name='modifierExperience'),
    path('supprimerExperience/<int:experience_id>/', supprimerExperience, name='supprimerExperience'),
    path('ajouterFormation/', ajouterFormation, name='ajouterFormation'),
    path('modifierFormation/<int:formation_id>/', modifierFormation, name='modifierFormation'),
    path('supprimerFormation/<int:formation_id>/', supprimerFormation, name='supprimerFormation'),
    path('inscription_entreprise/', inscription_entreprise, name='inscription_entreprise'),
    path('connexion_entreprise/', connexion_entreprise, name='connexion_entreprise'),
    path('profil_entreprise/', profil_entreprise, name='profil_entreprise'),
    path('modifier_profil_entreprise/<int:entreprise_id>', modifier_profil_entreprise, name='modifier_profil_entreprise'),
    path('publier_offre_emploi/', publier_offre_emploi, name='publier_offre_emploi'),
    path('modifier_offre/<int:emploi_id>/', modifier_offre, name='modifier_offre'),
    path('retirer_offre/<int:emploi_id>/', retirer_offre, name='retirer_offre'),
    path('candidats_par_entreprise/<int:entreprise_id>/', candidats_par_entreprise, name='candidats_par_entreprise'),
    path('modifier_statut_candidature/<int:postulation_id>/', modifier_statut_candidature, name='modifier_statut_candidature'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt'
    ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        form_class=CustomSetPasswordForm  # Utilisez votre formulaire personnalisé
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('chat_message/entreprise/<int:entreprise_id>/candidat/<int:candidat_id>/', chat_message, name='chat_message'),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Modèle pour représenter un candidat
class Candidat(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nom = models.CharField(max_length=50)  # Nom du candidat
    prenom = models.CharField(max_length=50)  # Prénom du candidat
    telephone = models.CharField(max_length=10, blank=True, null=True, unique=True)  # Numéro de téléphone du candidat (facultatif, unique)
    cv = models.FileField(upload_to='cv_files/', blank=True, null=True)  # Fichier CV du candidat (facultatif)
    ville = models.CharField(max_length=50, blank=True, null=True)  # Ville du candidat (facultatif)
    email = models.CharField(max_length=50, default='')  # Adresse e-mail du candidat (par défaut vide)

    def __str__(self):
        return self.nom + ' ' + self.prenom

# Modèle pour représenter une entreprise
class Entreprise(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nom = models.CharField(max_length=50)  # Nom de l'entreprise
    email = models.EmailField(max_length=100, default='')  # Adresse e-mail de l'entreprise (par défaut vide, longueur augmentée)
    telephone = models.CharField(max_length=10, blank=True, null=True, unique=True)  # Numéro de téléphone de l'entreprise (facultatif, unique)
    siren = models.CharField(max_length=9, blank=True, null=True, unique=True)  # Numéro SIREN de l'entreprise (facultatif, unique, longueur de 9 caractères)
    ville = models.CharField(max_length=50, blank=True, null=True)  # Ville de l'entreprise (facultatif)
    description = models.TextField(blank=True, null=True)  # Description de l'entreprise (facultatif)

    def __str__(self):
        return self.nom

# Modèle pour représenter les compétences des candidats
class Competence(models.Model):
    nom = models.CharField(max_length=50)  # Nom de la compétence
    niveau = models.CharField(max_length=50)  # Niveau de maîtrise de la compétence
    candidat = models.ForeignKey(Candidat, on_delete=models.CASCADE, related_name='competences')  # Clé étrangère liant la compétence au candidat

# Modèle pour représenter les formations des candidats
class Formation(models.Model):
    titre = models.CharField(max_length=50)  # Titre de la formation
    nom_ecole = models.CharField(max_length=50)  # Nom de l'école ou de l'institution
    ville = models.CharField(max_length=50)  # Ville de la formation
    dateDebut = models.DateField()  # Date de début de la formation
    dateFin = models.DateField()  # Date de fin de la formation
    candidat = models.ForeignKey(Candidat, on_delete=models.CASCADE, related_name='formations')  # Clé étrangère liant la formation au candidat

# Modèle pour représenter les expériences professionnelles des candidats
class Experience(models.Model):
    entreprise = models.CharField(max_length=50)  # Nom de l'entreprise
    poste = models.CharField(max_length=50)  # Poste occupé
    description = models.TextField(blank=True, null=True)  # Description de l'expérience (facultatif)
    dateDebut = models.DateField()  # Date de début de l'expérience
    dateFin = models.DateField()  # Date de fin de l'expérience
    candidat = models.ForeignKey(Candidat, on_delete=models.CASCADE, related_name='experiences')  # Clé étrangère liant l'expérience au candidat

# Modèle pour représenter les offres d'emploi
class Emploi(models.Model):
    titre = models.CharField(max_length=50)  # Titre de l'offre d'emploi
    description = models.TextField(blank=True, null=True)  # Description de l'offre d'emploi (facultatif)
    exigence = models.TextField(blank=True, null=True)  # Exigences de l'offre d'emploi (facultatif)
    ville = models.CharField(max_length=50)  # Ville de l'offre d'emploi
    salaire = models.DecimalField(max_digits=15, decimal_places=3, blank=True, null=True)  # Salaire de l'offre d'emploi (facultatif)
    type_contrat = models.CharField(max_length=50)  # Type de contrat de travail (CDI, CDD, etc.)
    domaine = models.CharField(max_length=50)  # Domaine de l'offre d'emploi
    datePublication = models.DateTimeField(auto_now_add=True)  # Date de publication de l'offre d'emploi
    entreprise = models.ForeignKey(Entreprise, on_delete=models.CASCADE, related_name='emplois')  # Clé étrangère liant l'offre d'emploi à l'entreprise

    def __str__(self):
        return self.titre

# Modèle pour représenter les candidatures aux offres d'emploi
class Postuler(models.Model):
    emploi = models.ForeignKey(Emploi, on_delete=models.CASCADE)  # Clé étrangère liant la candidature à l'offre d'emploi
    candidat = models.ForeignKey(Candidat, on_delete=models.CASCADE)  # Clé étrangère liant la candidature au candidat
    dateCandidature = models.DateField(auto_now_add=True)  # Date de la candidature
    lettreMotivation = models.TextField()  # Lettre de motivation du candidat pour la candidature
    statutCandidature = models.CharField(max_length=20, default='En attente')  # Statut de la candidature (En attente, Acceptée, Refusée, etc.)

# Modèle pour représenter les messages échangés entre l'entreprise et le candidat
class Message(models.Model):
    contenu = models.TextField()  # Contenu du message
    date_message = models.DateTimeField(auto_now_add=True)  # Date et heure du message
    expediteur = models.ForeignKey(User, on_delete=models.CASCADE)  # Clé étrangère liant l'expéditeur (utilisateur) au message

# Modèle pour représenter une conversation entre une entreprise et un candidat
class Conversation(models.Model):
    entreprise = models.ForeignKey(User, related_name='conversations_entreprise', on_delete=models.CASCADE)  # Clé étrangère liant l'entreprise à la conversation
    candidat = models.ForeignKey(User, related_name='conversations_candidat', on_delete=models.CASCADE)  # Clé étrangère liant le candidat à la conversation
    messages = models.ManyToManyField(Message)  # Relation ManyToMany pour les messages de la conversation

    class Meta:
        unique_together = ['entreprise', 'candidat']  # Contrainte pour garantir l'unicité de la conversation entre l'entreprise et le candidat

my_app/templates/entreprises/candidats_par_entreprise.html
<!DOCTYPE html>
<html>
<head>
    <title>Liste des candidats</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
            text-align: center;
            max-width: 70%;
            margin: 0 auto;
            background-color: #fff;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }

        h2 {
            color: #333;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        a {
            display: inline-block;
            background-color: #4CAF50;
            color: #fff;
            padding: 10px 20px;
            border-radius: 3px;
            text-decoration: none;
            margin-right: 10px;
            margin-bottom: 10px;
        }

        a:hover {
            background-color: #45a049;
        }

        p {
            color: #999;
            font-style: italic;
        }
        .refused {
            color: red;
        }

        .accepted {
            color: green;
        }
    </style>
</head>
<body>
    <h2>Liste des candidats ayant postulé aux offres d'emploi de l'entreprise {{ entreprise.nom }}</h2>
    {% if candidats %}
        <table>
            <tr>
                <th>Nom du candidat</th>
                <th>Date de candidature</th>
                <th>Lettre de motivation</th>
                <th>CV</th>
                <th>Titre de l'offre</th>
                <th>Description de l'offre</th>
                <th>Statut de candidature</th>
                <th>Modifier le statut</th>
                <th>Contacter le candidat</th>
            </tr>
            {% for candidat in candidats %}
                {% for postulation in candidat.postuler_set.all %}
                    {% if postulation.emploi.entreprise_id == entreprise_id %}
                        <tr>
                            <td><strong>{{ candidat.nom }} </strong> {{ candidat.prenom }}</td>
                            <td>{{ postulation.dateCandidature|date:"d/m/Y"}}</td>
                            <td>{{ postulation.lettreMotivation }}</td>
                            <td><a href="{{ postulation.candidat.cv.url }}" target="_blank"><i class="fas fa-eye"></i>Voir le CV</a></td>
                            <td>{{ postulation.emploi.titre }}</td>
                            <td><a href="{% url 'offre_emploi_detail' postulation.emploi.id %}" class="job-details-link"><i class="fas fa-eye"></i>Voir l'offre</a></td>
                            <td class="{% if postulation.statutCandidature == 'Refusée' %}refused{% else %}accepted{% endif %}">{{ postulation.statutCandidature }}</td>
                            <td><a href="{% url 'modifier_statut_candidature' postulation_id=postulation.id %}"><i class="fas fa-edit"></i> Modifier le statut</a></td>
                            <td><a href="{% url 'chat_message' entreprise_id=entreprise.id candidat_id=candidat.id %}"><i class="fas fa-envelope"></i> Contacter</a></td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            
        </table>
        <a href="{% url 'profil_entreprise' %}" class="btn btn-primary"><i class="fas fa-sign-out-alt"></i> Retour à mon profil</a>
    {% else %}
        <p>Aucun candidat n'a postulé aux offres d'emploi de cette entreprise pour le moment.</p>
    {% endif %}
</body>
</html>

my_app/templates/entreprises/connexion_entreprise.html
<!DOCTYPE html>
<html>
<head>
    <title>Connexion Candidat</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
            text-align: center;
        }

        h2 {
            color: #333;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            width: 300px;
            margin: 0 auto;
        }

        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
            text-align: left;
        }

        input[type="text"],
        input[type="password"],
        input[type="email"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-bottom: 15px;
        }

        button {
            background-color: #4CAF50;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h2>Connexion Entreprise</h2>
    <form method="post">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <ul>
                {% for error in form.non_field_errors %}
                    <li style="color: red;">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    
        <label for="{{ form.username.id_for_label }}">Email:</label>
        {{ form.username }}
        {% if form.username.errors %}
            <ul>
                {% for error in form.username.errors %}
                    <li style="color: red;">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    
        <label for="{{ form.password.id_for_label }}">Mot de passe:</label>
        {{ form.password }}
        {% if form.password.errors %}
            <ul>
                {% for error in form.password.errors %}
                    <li style="color: red;">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    
        <button type="submit">Se connecter</button>
    </form>
    <div class="container">
        <h2 class="reset-message-heading">Mot de passe oublié ?</h2>
        <p class="reset-message">Si vous avez oublié votre mot de passe, pas de souci ! Cliquez sur le lien ci-dessous pour renouveler votre mot de passe.</p>
        <a href="{% url 'password_reset' %}" class="btn btn-primary">
          <i class="fas fa-key"></i> Renouveler mon mot de passe</a>
    </div>
</body>
</html>

my_app/templates/entreprises/inscription_entreprise.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Inscription Entreprise</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> 
    <style>
        /* Votre style CSS personnalisé ici */
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
        }

        h2 {
            color: #333;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }

        input[type="text"],
        input[type="password"],
        input[type="email"] {
            width: 50%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-bottom: 15px;
        }

        .error-message {
            color: red;
            font-size: 12px;
            margin-top: 5px;
        }

        button {
            background-color: #4CAF50;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h2>Inscription Entreprise</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="{{ entreprise_form.nom.id_for_label }}">Nom:</label>
        {{ entreprise_form.nom }}
        <br><br>

        <label for="{{ entreprise_form.siren.id_for_label }}">Siren:</label>
        {{ entreprise_form.siren }}
        <span class="error-message">{{ entreprise_form.siren.errors }}</span>
        
        <br><br>

        <label for="{{ entreprise_form.ville.id_for_label }}">Ville:</label>
        {{ entreprise_form.ville }}
        <br><br>

        <label for="{{ entreprise_form.telephone.id_for_label }}">Téléphone:</label>
        {{ entreprise_form.telephone }}
        <span class="error-message">{{ entreprise_form.telephone.errors }}</span>
        <br><br>

        <label for="{{ entreprise_form.description.id_for_label }}">Description:</label>
        {{ entreprise_form.description }}
        <br><br>

        <label for="{{ user_form.email.id_for_label }}">Email:</label>
        {{ user_form.email }}
        <br><br>

        <div class="password-container">
            <label for="{{ user_form.password.id_for_label }}">Mot de passe:</label>
            {{ user_form.password }}
            <span class="error-message">{{ user_form.password.errors }}</span>
        </div>
        <br><br>

        <label for="{{ user_form.confirm_password.id_for_label }}">Confirmez le mot de passe:</label>
        {{ user_form.confirm_password }}
        <span class="error-message">{{ user_form.confirm_password.errors }}</span>
        <br><br>

        <button type="submit">S'inscrire</button>
        <a href="{% url 'home' %}" class="btn btn-secondary"><i class="fas fa-times"></i> Annuler</a>
    </form>
</body>
</html>

my_app/templates/entreprises/modifier_offre.html
<!DOCTYPE html>
<html>
<head>
    <title>Modifier l'offre d'emploi</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> 
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
            text-align: center;
        }

        h2 {
            color: #333;
            margin-bottom: 20px;
        }

        form {
            display: inline-block;
            text-align: left;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 3px;
            border: 1px solid #ccc;
        }

        button[type="submit"] {
            display: inline-block;
            background-color: #4CAF50;
            color: #fff;
            padding: 10px 20px;
            border-radius: 3px;
            text-decoration: none;
            margin-right: 10px;
        }

        button[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h2>Modifier l'offre d'emploi</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enregistrer</button>
        <a href="{% url 'profil_entreprise' %}" class="btn btn-secondary"><i class="fas fa-times"></i> Annuler</a>
    </form>
</body>
</html>

my_app/templates/entreprises/modifier_profil_entreprise.html
<!DOCTYPE html>
<html>
<head>
    <title>Mettre à jour mes données personnelles</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
  font-family: Arial, sans-serif;
  background-color: #f2f2f2;
  padding: 20px;
  text-align: center;
}

h2 {
  color: #333;
  margin-bottom: 20px;
}

form {
  display: inline-block;
  text-align: left;
  margin: 0 auto;
  max-width: 400px;
}

form label {
  display: block;
  font-weight: bold;
  margin-bottom: 5px;
}

input[type="text"],
textarea {
  width: 100%;
  padding: 10px;
  margin-bottom: 10px;
  border-radius: 3px;
  border: 1px solid #ccc;
}

button[type="submit"] {
  display: inline-block;
  background-color: #4CAF50;
  color: #fff;
  padding: 10px 20px;
  border-radius: 3px;
  text-decoration: none;
  margin-right: 10px;
}

button[type="submit"]:hover {
  background-color: #45a049;
}
.error {
            color: red;
        }

        
    </style>
</head>
<body>
  <h2>Mettre à jour mes données personnelles</h2>
  <form method="post">
      {% csrf_token %}
      {% for field in form %}
          <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field }}
              <div class="error">
                  {% for error in field.errors %}
                      {{ error }}
                  {% endfor %}
              </div>
          </div>
      {% endfor %}
      <button type="submit">Enregistrer</button>
      <a href="{% url 'profil_entreprise' %}" class="btn btn-secondary"><i class="fas fa-times"></i> Annuler</a>
  </form>

</body>
</html>

my_app/templates/entreprises/modifier_statut_candidature.html
<!DOCTYPE html>
<html>
<head>
    <title>Modifier le statut de la candidature</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> 
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
            text-align: center;
        }

        h2 {
            color: #333;
            margin-bottom: 20px;
        }

        form {
            display: inline-block;
            text-align: left;
            background-color: #fff;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }

        input[type="submit"] {
            display: inline-block;
            background-color: #4CAF50;
            color: #fff;
            padding: 10px 20px;
            border-radius: 3px;
            text-decoration: none;
            margin-top: 10px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h2>Modifier le statut de la candidature</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enregistrer</button>
        <a href="{% url 'profil_entreprise' %}" class="btn btn-secondary"><i class="fas fa-times"></i> Annuler</a>
    </form>
</body>
</html>

my_app/templates/entreprises/publier_offre.html
<!DOCTYPE html>
<html>
<head>
    <title>Publier une offre d'emploi</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> 
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
            text-align: center;
        }

        h2 {
            color: #333;
            margin-bottom: 20px;
        }

        form {
            display: inline-block;
            text-align: left;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 3px;
            border: 1px solid #ccc;
        }

        button[type="submit"] {
            display: inline-block;
            background-color: #4CAF50;
            color: #fff;
            padding: 10px 20px;
            border-radius: 3px;
            text-decoration: none;
            margin-right: 10px;
        }

        button[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h2>Publier une offre d'emploi</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Publier</button>
        <a href="{% url 'profil_entreprise' %}" class="btn btn-secondary"><i class="fas fa-times"></i> Annuler</a>
    </form>
</body>
</html>